---
title: "Project1"
author: "Jasper Drumm, Leif Gullstad, Thomas Papesh, Aidan Hatzer, Jonah Cuenca"
date: "2022-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Downloading and Prepping the Data

```{r}
#Downloading and Prepping the Data
tele <- read.csv("tele.csv", stringsAsFactors = TRUE)
summary(tele)

#We are deleting the "duration" variable because it is an after the fact measurement. We only should be using variables that we know before the call
tele$duration <- NULL

# Deleting the column X
tele$X <- NULL

# Changing pdays to a dummy and deleting pdays
tele$pdaysdummy <- ifelse(tele$pdays == 999, 0, 1)
tele$pdays <- NULL

str(tele)
```

## Getting Data Ready for Analysis

```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

telemm <- as.data.frame(model.matrix(~.-1,tele))
str(telemm)

# Randomize the rows in the data (shuffling the rows)
set.seed(12345)
tele_random <- telemm[sample(nrow(telemm)),]

#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything 
tele_norm <- as.data.frame(lapply(tele_random, normalize))
```


## Getting Train and Test Samples

```{r}
# Selects 10000 random rows for test data
set.seed(12345)
test_set <- sample(1:nrow(tele_norm), 10000) 
# Depending on R-version and computer, different rows may be selected. 
# If that happens, results are different. 

# Create a train set and test set
#First the predictors - all columns except the yyes column
tele_train <- tele_norm[-test_set, -match("yyes",names(tele_norm))]
tele_test <- tele_norm[test_set, -match("yyes",names(tele_norm))]

#Now the response (aka Labels) - only the yyes column
tele_train_labels <- tele_norm[-test_set, "yyes"]
tele_test_labels <- tele_norm[test_set, "yyes"]

```

> Now you are ready to build your ANN model. Feel free to modify the data load, cleaning and preparation code above as per your preference.

## Get Train and Test Samples for ANN
```{r}
set.seed(12345)

tele_sample<- sample(1:nrow(tele_norm), 10000)
tele_test <- tele_norm[tele_sample,]
tele_train <- tele_norm[-tele_sample,]
```

## Train an ANN model on telemarketing data
```{r, cache=T}
library(neuralnet)

tele_model <- neuralnet(formula = yyes~.,
                              data = tele_train, hidden = 5)

# hidden = c(9,7,4)
```

## Evaluate ANN model performance
```{r}
library(caret)

plot(tele_model)
tele_prediction <- predict(tele_model, newdata = tele_test, type = "response")
tele_prediction <- ifelse(tele_prediction < 0.5, 0, 1)

confusionMatrix(as.factor(tele_test$yyes), as.factor(tele_prediction))
```
